language: python
python:
  - 2.7
  - 3.4
  - 3.5
addons:
  postgresql: "9.3"
install:
  - pip install -i http://tools.pacificclimate.org/pypiserver/ -r requirements.txt -r test_requirements.txt
  - pip install .
script: py.test -v --tb=short tests
