dist: bionic
language: python
python:
  - 3.6
  - 3.7
addons:
  postgresql: "9.3"
  apt:
      packages:
        - postgresql-plpython-9.3
        - postgresql-9.3-postgis-2.4
install:
  - pip install -U pip
  - pip install -i https://pypi.pacificclimate.org/simple/ -r requirements.txt -r test_requirements.txt
  - pip install -i https://pypi.pacificclimate.org/simple/ .
# We are currently not running the weather_anomaly tests because the functions
# they depend on have been moved into a migration. Once views and matviews have
# been moved into migrations, these tests will be transferred into specific
# migration tests.
script: PYCDS_SCHEMA_NAME=other py.test -v --tb=short -k "not weather_anomal" tests
