name: Code format check

on: push

jobs:
  check:

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install project and black
        run: |
          poetry run pip install .[dev]

      - name: Run check
        run: poetry run black . --check
