name: Python CI Partial

on: push

jobs:
  test:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      env:
        PIP_INDEX_URL: https://pypi.pacificclimate.org/simple
      run: |
        sudo apt-get install postgresql-plpython-9.5 postgresql-9.5-postgis-2.4
    - name: Explore
      run: |
        sudo apt-cache showpkg postgresql-plpython-9.5
